# Generated by Django 4.1.6 on 2025-02-27 19:48

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('illness_predictor', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='illnessprediction',
            name='created_at',
        ),
        migrations.RemoveField(
            model_name='illnessprediction',
            name='predicted_disease',
        ),
        migrations.AlterField(
            model_name='illnessprediction',
            name='user',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
    ]
